version: '3'
services:
  web:
    depends_on:
      - db
    build: poemApp
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb.d/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: poem
    networks:
      - backend
networks:
  frontend:
  backend:
volumes:
  db_data:
