version: '3'
services:
  web:
    depends_on:
      - db
    build: poemApp
    restart: always
    ports:
      - "443:3000"
    networks:
      - frontend
      - backend
  db:
    image: mysql:latest
    restart: always
    command: mysqld --character-set-server utf8mb4 --collation-server utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./DB/initdb.d/:/docker-entrypoint-initdb.d
      - ./DB/mysql.cnf:/etc/mysql/conf.d/mysql_.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: poem
      TZ: "Asia/Tokyo"
    networks:
      - backend
networks:
  frontend:
  backend:
volumes:
  db_data:
