CREATE TABLE IF NOT EXISTS poem.blogs (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `text` MEDIUMTEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
   PRIMARY KEY (`id`)
  );
